# Generated by make-pins.py, do NOT edit!
PINS_AF = (
  ('LED1', (1, 'LPUART8_CTS_B'), (3, 'GPT2_COMPARE3'), (4, 'FLEXPWM1_PWMA2'), (5, 'GPIO3_PIN3'), (10, 'GPIO9_PIN3'), ),
  ('LED2', (0, 'LPUART1_CTS_B'), (1, 'LPSPI2_SDO'), (4, 'FLEXPWM2_PWMA1'), (5, 'GPIO3_PIN25'), (10, 'GPIO9_PIN25'), ),
)
