// Generated by make-pins.py, do NOT edit!
extern const pin_obj_t pin_AD_04;
extern const pin_af_obj_t pin_AD_04_af[];
extern const pin_obj_t pin_AD_26;
extern const pin_af_obj_t pin_AD_26_af[];
extern const pin_obj_t * const pin_adc1[];
extern const pin_obj_t * const pin_adc2[];
extern const pin_obj_t * const pin_adc3[];
#define pyb_pin_LED1 pin_AD_04
#define pyb_pin_LED2 pin_AD_26
