Import('RTT_ROOT')
Import('rtconfig')
from building import *
import os

# add the general drivers.
src = Split("""
board.c
MCUX_Config/clock_config.c
MCUX_Config/pin_mux.c
""")

if GetDepend(['NXP_USING_MICROPYTHON']):
	print("Generate PINs files...")
	cmd = 'python .\make-pins.py -b .\pins.csv --af .\mimxrt105x_af.csv --pinmap .\mimxrt105x_pinmap.csv --prefix mimxrt105x_prefix.c --qstr .\pins_qstr.h --af-const .\pins_af_const.h --af-py .\pins_af.py > pins_imxrtevk106x.c'
	os.popen(cmd)
	src += ['pins_imxrtevk106x.c']
cwd = GetCurrentDir()


CPPPATH = [cwd,cwd + '/MCUX_Config',cwd + '/ports']
CPPDEFINES = ['CPU_MIMXRT1062DVL6A', 'STD=C99', 'SKIP_SYSCLK_INIT', 'EVK_MCIMXRM', 'FSL_SDK_ENABLE_DRIVER_CACHE_CONTROL','XIP_EXTERNAL_FLASH=1', 'XIP_BOOT_HEADER_ENABLE=1,XIP_BOOT_HEADER_DCD_ENABLE=1,ARM_MATH_CM7,__FPU_PRESENT,FFCONF_H=\"oofatfs/ffconf.h\",HARD_FP,FSL_SDK_ENABLE_DRIVER_CACHE_CONTROL=1']

LOCAL_CCFLAGS = ''    
if rtconfig.CROSS_TOOL == 'gcc':
    LOCAL_CCFLAGS += ' -std=c99'
elif rtconfig.CROSS_TOOL == 'keil':
    LOCAL_CCFLAGS += ' --c99 --gnu'
    
group = DefineGroup('Drivers', src, depend = [''], CPPPATH = CPPPATH, CPPDEFINES=CPPDEFINES)

Return('group')
